/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MoveList {
        "moves": [];
    }
    interface NumInput {
        "func": any;
        "no": number;
    }
    interface PokedexClass {
    }
    interface PokemonSprite {
        "src": any;
    }
}
declare global {
    interface HTMLMoveListElement extends Components.MoveList, HTMLStencilElement {
    }
    var HTMLMoveListElement: {
        prototype: HTMLMoveListElement;
        new (): HTMLMoveListElement;
    };
    interface HTMLNumInputElement extends Components.NumInput, HTMLStencilElement {
    }
    var HTMLNumInputElement: {
        prototype: HTMLNumInputElement;
        new (): HTMLNumInputElement;
    };
    interface HTMLPokedexClassElement extends Components.PokedexClass, HTMLStencilElement {
    }
    var HTMLPokedexClassElement: {
        prototype: HTMLPokedexClassElement;
        new (): HTMLPokedexClassElement;
    };
    interface HTMLPokemonSpriteElement extends Components.PokemonSprite, HTMLStencilElement {
    }
    var HTMLPokemonSpriteElement: {
        prototype: HTMLPokemonSpriteElement;
        new (): HTMLPokemonSpriteElement;
    };
    interface HTMLElementTagNameMap {
        "move-list": HTMLMoveListElement;
        "num-input": HTMLNumInputElement;
        "pokedex-class": HTMLPokedexClassElement;
        "pokemon-sprite": HTMLPokemonSpriteElement;
    }
}
declare namespace LocalJSX {
    interface MoveList {
        "moves"?: [];
    }
    interface NumInput {
        "func"?: any;
        "no"?: number;
    }
    interface PokedexClass {
    }
    interface PokemonSprite {
        "src"?: any;
    }
    interface IntrinsicElements {
        "move-list": MoveList;
        "num-input": NumInput;
        "pokedex-class": PokedexClass;
        "pokemon-sprite": PokemonSprite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "move-list": LocalJSX.MoveList & JSXBase.HTMLAttributes<HTMLMoveListElement>;
            "num-input": LocalJSX.NumInput & JSXBase.HTMLAttributes<HTMLNumInputElement>;
            "pokedex-class": LocalJSX.PokedexClass & JSXBase.HTMLAttributes<HTMLPokedexClassElement>;
            "pokemon-sprite": LocalJSX.PokemonSprite & JSXBase.HTMLAttributes<HTMLPokemonSpriteElement>;
        }
    }
}
